import '../models/bible_book.dart';

/// DB/API에서 사용하는 book 코드(3글자)를 id로 사용합니다.
/// (예: GEN, EXO, PSA ...)
///
/// ※ 현재 서버/DB가 이 코드를 쓰는 구조라면 Flutter도 동일해야 합니다.
const bibleBooks = <BibleBook>[
  // 구약
  BibleBook(id: 'GEN', koName: '창세기', chapters: 50),
  BibleBook(id: 'EXO', koName: '출애굽기', chapters: 40),
  BibleBook(id: 'LEV', koName: '레위기', chapters: 27),
  BibleBook(id: 'NUM', koName: '민수기', chapters: 36),
  BibleBook(id: 'DEU', koName: '신명기', chapters: 34),
  BibleBook(id: 'JOS', koName: '여호수아', chapters: 24),
  BibleBook(id: 'JDG', koName: '사사기', chapters: 21),
  BibleBook(id: 'RUT', koName: '룻기', chapters: 4),
  BibleBook(id: '1SA', koName: '사무엘상', chapters: 31),
  BibleBook(id: '2SA', koName: '사무엘하', chapters: 24),
  BibleBook(id: '1KI', koName: '열왕기상', chapters: 22),
  BibleBook(id: '2KI', koName: '열왕기하', chapters: 25),
  BibleBook(id: '1CH', koName: '역대상', chapters: 29),
  BibleBook(id: '2CH', koName: '역대하', chapters: 36),
  BibleBook(id: 'EZR', koName: '에스라', chapters: 10),
  BibleBook(id: 'NEH', koName: '느헤미야', chapters: 13),
  BibleBook(id: 'EST', koName: '에스더', chapters: 10),
  BibleBook(id: 'JOB', koName: '욥기', chapters: 42),
  BibleBook(id: 'PSA', koName: '시편', chapters: 150),
  BibleBook(id: 'PRO', koName: '잠언', chapters: 31),
  BibleBook(id: 'ECC', koName: '전도서', chapters: 12),
  BibleBook(id: 'SNG', koName: '아가', chapters: 8),
  BibleBook(id: 'ISA', koName: '이사야', chapters: 66),
  BibleBook(id: 'JER', koName: '예레미야', chapters: 52),
  BibleBook(id: 'LAM', koName: '예레미야애가', chapters: 5),
  BibleBook(id: 'EZK', koName: '에스겔', chapters: 48),
  BibleBook(id: 'DAN', koName: '다니엘', chapters: 12),
  BibleBook(id: 'HOS', koName: '호세아', chapters: 14),
  BibleBook(id: 'JOL', koName: '요엘', chapters: 3),
  BibleBook(id: 'AMO', koName: '아모스', chapters: 9),
  BibleBook(id: 'OBA', koName: '오바댜', chapters: 1),
  BibleBook(id: 'JON', koName: '요나', chapters: 4),
  BibleBook(id: 'MIC', koName: '미가', chapters: 7),
  BibleBook(id: 'NAM', koName: '나훔', chapters: 3),
  BibleBook(id: 'HAB', koName: '하박국', chapters: 3),
  BibleBook(id: 'ZEP', koName: '스바냐', chapters: 3),
  BibleBook(id: 'HAG', koName: '학개', chapters: 2),
  BibleBook(id: 'ZEC', koName: '스가랴', chapters: 14),
  BibleBook(id: 'MAL', koName: '말라기', chapters: 4),

  // 신약
  BibleBook(id: 'MAT', koName: '마태복음', chapters: 28),
  BibleBook(id: 'MRK', koName: '마가복음', chapters: 16),
  BibleBook(id: 'LUK', koName: '누가복음', chapters: 24),
  BibleBook(id: 'JHN', koName: '요한복음', chapters: 21),
  BibleBook(id: 'ACT', koName: '사도행전', chapters: 28),
  BibleBook(id: 'ROM', koName: '로마서', chapters: 16),
  BibleBook(id: '1CO', koName: '고린도전서', chapters: 16),
  BibleBook(id: '2CO', koName: '고린도후서', chapters: 13),
  BibleBook(id: 'GAL', koName: '갈라디아서', chapters: 6),
  BibleBook(id: 'EPH', koName: '에베소서', chapters: 6),
  BibleBook(id: 'PHP', koName: '빌립보서', chapters: 4),
  BibleBook(id: 'COL', koName: '골로새서', chapters: 4),
  BibleBook(id: '1TH', koName: '데살로니가전서', chapters: 5),
  BibleBook(id: '2TH', koName: '데살로니가후서', chapters: 3),
  BibleBook(id: '1TI', koName: '디모데전서', chapters: 6),
  BibleBook(id: '2TI', koName: '디모데후서', chapters: 4),
  BibleBook(id: 'TIT', koName: '디도서', chapters: 3),
  BibleBook(id: 'PHM', koName: '빌레몬서', chapters: 1),
  BibleBook(id: 'HEB', koName: '히브리서', chapters: 13),
  BibleBook(id: 'JAS', koName: '야고보서', chapters: 5),
  BibleBook(id: '1PE', koName: '베드로전서', chapters: 5),
  BibleBook(id: '2PE', koName: '베드로후서', chapters: 3),
  BibleBook(id: '1JN', koName: '요한일서', chapters: 5),
  BibleBook(id: '2JN', koName: '요한이서', chapters: 1),
  BibleBook(id: '3JN', koName: '요한삼서', chapters: 1),
  BibleBook(id: 'JUD', koName: '유다서', chapters: 1),
  BibleBook(id: 'REV', koName: '요한계시록', chapters: 22),
];