const Map<String, String> koBookAliasToId = {
  '창': 'Genesis',
  '창세기': 'Genesis',
  '출': 'Exodus',
  '출애굽기': 'Exodus',
  '시': 'Psalms',
  '시편': 'Psalms',
  '잠': 'Proverbs',
  '잠언': 'Proverbs',

  '마': 'Matthew',
  '마태': 'Matthew',
  '마태복음': 'Matthew',
  '막': 'Mark',
  '마가': 'Mark',
  '마가복음': 'Mark',
  '눅': 'Luke',
  '누가': 'Luke',
  '누가복음': 'Luke',
  '요': 'John',
  '요한': 'John',
  '요한복음': 'John',

  '행': 'Acts',
  '사도행전': 'Acts',
  '롬': 'Romans',
  '로마서': 'Romans',
  '계': 'Revelation',
  '요한계시록': 'Revelation',
};
